### ISSUE TITLE
flatpak install version 18.08

### ISSUE THREAD

**Issue by abienz** [flathub/io.elementary.BaseApp#12]
When I run `flatpak install io.elementary.BaseApp` the version I get is Juno 18.08 but I see that 19.08 is that latest version and the default branch here.

Has this release been pushed to flathub yet? If not is there an ETA as I require it as a dependency for a project I'm building.

**Comment by barthalion** [comment]
You need to specify the branch to install, so `io.elementary.BaseApp//juno-19.08` instead should work.

**Comment by abienz** [comment]
Thanks, I didn't find any information about branches on Flatpak or Flathub websites, if you hadn't had mentioned it I wouldn't have known.

It worked for me.
