### ISSUE TITLE
Missing version after building.

### ISSUE THREAD

**Issue by jeremypw** [flathub/io.elementary.BaseApp#18]
After building and installing the juno-20.08 branch with 
`flatpak-builder --force-clean --install --user <build-dir> ./io.elementary.BaseApp.yml`, it was not possible to use the BaseApp to build e.g. io.elementary.code flatpak because the installed BaseApp had no version number (and the Code manifest specifies "juno-20.08") and the default branch is not named "master".

This was fixed by inserting `branch: juno-20.08` into the BaseApp manifest

**Comment by bilelmoussaoui** [comment]
It should be needed as flathub sets that branch based on the git branch. That's why it didn't work when you built it locally.

**Comment by jeremypw** [comment]
OK, so its not a issue with this repo then.  Thanks,.
