### ISSUE TITLE
Elementary Odin released

### ISSUE THREAD

**Issue by albfan** [flathub/io.elementary.BaseApp#19]
https://blog.elementary.io/elementary-os-6-odin-released/

Wonder if elementary flatpak reviews from @danrabbit https://twitter.com/DanielFore/status/1425879304253018112?s=20 are for oldest elementary releases.

Would be really interesting to upgrade this base app, and maybe add a hint about which release it is

https://github.com/elementary/stylesheet/releases

io.elementary.BaseApp:6.0.0 makes more sense to me than io.elementary.BaseApp:20.08

This relates with https://github.com/flathub/com.github.akiraux.akira/issues/5

**Comment by hfiguiere** [comment]
20.08 is the freedesktop runtime. But then it's juno-20.08. Not sure what Juno is but maybe it should be odin-20.08 for this new version? (21.08 is coming soon)

**Comment by bilelmoussaoui** [comment]
I don't think we want to continue using this baseapp now that elementary released their SDK

**Comment by tim77** [comment]
So, maybe we should EOL Elementary Apps on Flathub? One Elementary app which i need to update already required new v6 but seems like still working with current juno-20.08. Need to test it more though.

**Comment by gasinvein** [comment]
@bilelmoussaoui What's the future of eOS apps on Flathub in general? Since eOS opened their own flatpak repository, shouldn't all the "made for eOS" apps be moved there?

**Comment by albfan** [comment]
I just check my own mention to elementary app reviews and found:

https://github.com/Alecaddd/taxi/blob/master/com.github.alecaddd.taxi.yml#L3

We're you can see the dedicated flatpak sdk and runtime

**Comment by albfan** [comment]
FTR:

```
runtime: io.elementary.Platform
runtime-version: '6'
sdk: io.elementary.Sdk
```

**Comment by hfiguiere** [comment]
if we had it in flathub, it wouldn't be a problem.

I feels like it's just fragmentation

**Comment by albfan** [comment]
@hfiguiere then the question is who to ask to distribute elementary runtime and sdk from flathub, not sure who will be that person.

this page, suggest that support elementary from flathub is expected: https://flatpak.org/setup/elementary%20OS/

Question posted on flathub forum: https://discourse.flathub.org/t/distributing-runtimes-and-sdk/1640
