### ISSUE TITLE
Add GTK4

### ISSUE THREAD

**Issue by ryonakano** [flathub/io.elementary.BaseApp#26]
### Problem

GTK4 isn't included in neither io.elementary.BaseApp or the fd.o runtime, so you can't build GTK4 apps using this runtime.

### Proposal

The maintainers of fd.o runtime [expects](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1599#note_1416869335) that we should use GNOME runtime if we need GTK4. So, we should either:

- A. Add GTK4 to the modules
- B. Switch the based runtime from fd.o to the GNOME that comes with GTK4
  - We no longer need graphviz, vala, and libgee too in this case

**Comment by hfiguiere** [comment]
use the gnome runtime. GNOME 47 in that case. It also includes vala.
