### ISSUE TITLE
Base app incompatible with gnome 3.32

### ISSUE THREAD

**Issue by alexlarsson** [flathub/io.elementary.BaseApp#7]
It seems like if you use this base app with the new 3.32 gnome runtime you run into some kind of incompatibility between gobject-introspection and vapigen, causing vapigen to loop forever printing errors. See e.g.: https://github.com/flathub/com.github.calo001.fondo/issues/3

This is pretty bad, as people seem to update their app without testing them locally, which is making flathub do poorly with megabytes of infinite spew.

**Comment by bilelmoussaoui** [comment]
A fast fix is already thanks to @alatiera there until we properly fix it.

**Comment by alexlarsson** [comment]
I published this build, so hopefully we should be ok now.

**Comment by bilelmoussaoui** [comment]
This can be closed I suppose
